version: '3.8'

services:
  http-server:
    image: python:3.9
    command: python -m http.server 8000
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "8000:8000"